add notFoundPage
fs-apr24-ConCats/ConCats-group-project pull request #6
Opened 2024-07-25 12:20 UTC by OleksiiKnihin

added notFoundPage and changed img for this page

2024-07-25 16:20 UTC, Kasprukov requested changes
Good job! 🔥

2024-07-25 16:20 UTC, Kasprukov commented on src/pages/notFoundPage/NotFoundPage.tsx
> +import './NotFoundPage.scss';
We agreed to use styles like this:
```suggestion
import classes from './NotFoundPage.module.scss';
```

2024-07-25 16:20 UTC, Kasprukov commented on src/pages/notFoundPage/NotFoundPage.tsx
> +    <div className="pageNotFound__wrapper">
Do this changes for all classes.
```suggestion
    <div className={classes.pageNotFound__wrapper}>
```

2024-07-26 12:39 UTC, FaiHamid approved these changes
Well done))

2024-07-26 12:42 UTC, Kasprukov approved these changes
Well done! 🔥

2024-07-26 12:44 UTC, merged